trigger:
- master

pool: Self-hosted

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    vstsFeed: '1c06c9e6-0aee-4aee-9efd-dd2216b649ca'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
