trigger:
- master

pool: Self-hosted

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    vstsFeed: '1c06c9e6-0aee-4aee-9efd-dd2216b649ca'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '-c $(buildConfiguration) --no-restore'
